"""baseline schema

Revision ID: f9849169d73f
Revises: 
Create Date: 2026-06-25 21:40:34.977340
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9849169d73f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('alertdestination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertdestination', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertdestination_user_id'), ['user_id'], unique=False)

    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_suffix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('readonly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apikey_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_apikey_user_id'), ['user_id'], unique=False)

    op.create_table('extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('permissions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('store_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('watchlist', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store', 'extension_id')
    )
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_user_id'), ['user_id'], unique=False)

    op.create_table('alertrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['alertdestination.id'], ),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertrule_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertrule_user_id'), ['user_id'], unique=False)

    op.create_table('fetchlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_score_before', sa.Integer(), nullable=True),
    sa.Column('risk_score_after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetchlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetchlog_extension_id'), ['extension_id'], unique=False)

    op.create_table('installcounthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installcounthistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installcounthistory_extension_id'), ['extension_id'], unique=False)

    op.create_table('alertlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['alertdestination.id'], ),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alertrule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertlog_extension_id'), ['extension_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertlog_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertlog_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertlog_user_id'))
        batch_op.drop_index(batch_op.f('ix_alertlog_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alertlog_extension_id'))

    op.drop_table('alertlog')
    with op.batch_alter_table('installcounthistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installcounthistory_extension_id'))

    op.drop_table('installcounthistory')
    with op.batch_alter_table('fetchlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetchlog_extension_id'))

    op.drop_table('fetchlog')
    with op.batch_alter_table('alertrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertrule_user_id'))
        batch_op.drop_index(batch_op.f('ix_alertrule_destination_id'))

    op.drop_table('alertrule')
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_user_id'))

    op.drop_table('extension')
    with op.batch_alter_table('apikey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apikey_user_id'))
        batch_op.drop_index(batch_op.f('ix_apikey_key_hash'))

    op.drop_table('apikey')
    with op.batch_alter_table('alertdestination', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertdestination_user_id'))

    op.drop_table('alertdestination')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
