import logging
from collections.abc import AsyncGenerator
from pathlib import Path

from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from sqlalchemy import inspect
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from sqlmodel.ext.asyncio.session import AsyncSession

from alembic import command
from app.config import settings

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent

# The revision a pre-Alembic database's schema actually corresponds to: the
# baseline was autogenerated from the models at adoption time (#11), and every
# later migration postdates all databases created by the retired
# create_all/_migrate_* path. Immutable history — never bump this.
_PRE_ALEMBIC_BASELINE = "f9849169d73f"

engine: AsyncEngine = create_async_engine(
    settings.database_url,
    echo=False,
    pool_size=5,
    max_overflow=10,
    pool_pre_ping=True,
    pool_timeout=30,
    pool_recycle=1800,  # Recycle connections every 30 min to avoid server-side idle timeouts
)


def _alembic_config() -> Config:
    """Programmatic Alembic config.

    Built without the .ini file so env.py's ``fileConfig`` (logging override) is
    skipped — the ini is only for the ``alembic`` CLI. script_location is set
    explicitly so the config works regardless of the process cwd.
    """
    cfg = Config()
    cfg.set_main_option("script_location", str(_PROJECT_ROOT / "alembic"))
    return cfg


def _run_migrations(sync_conn) -> None:
    """Bring the database to head, adopting pre-Alembic databases by stamping.

    Runs on a sync connection handed in by ``run_sync``. Six cases:
    - alembic_version present, core tables exist → ``upgrade head`` applies any
      new revisions.
    - no alembic_version, core tables already exist AND the schema is post-baseline
      (an unstamped ``create_all``'d head schema — the state an aborted test run
      leaves a dev DB in, since conftest drops alembic_version and create_all builds
      the head schema; #199) → stamp *head* and no-op the upgrade. Stamping the
      baseline here (the next case) would re-run post-baseline migrations against
      columns create_all already made → DuplicateColumn on the next boot.
    - no alembic_version, core tables already exist with the *baseline* schema (a
      database created by the old create_all/_migrate_* path) → stamp it at the
      *baseline* revision its schema actually matches (WITHOUT recreating anything),
      then upgrade to head like everyone else.
    - alembic_version present but the schema is *gone* (stamped-but-empty — e.g.
      a dev DB whose app tables were dropped out from under a surviving
      alembic_version, #113) → reset the stamp to base so the upgrade rebuilds
      from scratch instead of trusting the lying stamp and running nothing.
    - alembic_version present but the schema is still baseline-era (a database
      corrupted by the retired stamp-to-head adoption, #143) → re-stamp it at
      the baseline and upgrade, repairing the false stamp.
    - empty database → ``upgrade head`` creates everything from the baseline.
    """
    cfg = _alembic_config()
    cfg.attributes["connection"] = sync_conn

    has_user = "user" in inspect(sync_conn).get_table_names()
    current = MigrationContext.configure(sync_conn).get_current_revision()
    if current is None and has_user and _has_post_baseline_schema(sync_conn):
        # An unstamped schema that already matches head — NOT a pre-Alembic database.
        # This is the state an interrupted test run leaves a dev DB in: conftest drops
        # alembic_version and create_all builds the current (head) schema, so an aborted
        # suite leaves head-schema-with-no-stamp. Stamping the baseline (the branch below)
        # would then run every post-baseline migration against columns create_all already
        # made → DuplicateColumn, and the next `make dev` boot crashes (#199). Adopt it as
        # head instead — create_all builds from models.py, which test_head_matches_models
        # pins to the Alembic head, so the upgrade below is a no-op. Unreachable in
        # production, which never runs create_all.
        logger.info("Adopting an unstamped create_all'd head schema — stamping head (#199)")
        command.stamp(cfg, "head")
    elif current is None and has_user:
        # A pre-Alembic database matches the BASELINE schema, not head — stamping
        # head would mark every post-baseline migration as applied without running
        # it, with no recovery path (upgrade becomes a permanent no-op) (#143).
        logger.info("Adopting existing pre-Alembic database — stamping baseline, then upgrading")
        command.stamp(cfg, _PRE_ALEMBIC_BASELINE)
    elif current is not None and not has_user:
        # Stamped at a revision but the core schema is missing — the version table
        # is lying (#113). Trusting it would run no migrations and leave the app to
        # meet an empty schema. Reset to base so the upgrade below recreates
        # everything from scratch. Only reachable in a broken dev DB: production
        # never drops tables, so a real deployment can't hit this branch.
        logger.warning(
            "Database is stamped at %s but the core schema is missing — resetting to base and rebuilding (#113)",
            current,
        )
        command.stamp(cfg, "base")
    elif current is not None and _is_falsely_stamped_baseline(sync_conn, current):
        # The retired adoption stamped pre-Alembic databases at whatever head was
        # at the time, without running any DDL — leaving the baseline schema
        # marked as fully migrated. Re-stamp at the baseline it actually has so
        # the upgrade below finally applies the skipped migrations (#143).
        logger.warning(
            "Database claims revision %s but still has the baseline-era schema "
            "(falsely stamped by the retired adoption path, #143) — re-stamping baseline and upgrading",
            current,
        )
        command.stamp(cfg, _PRE_ALEMBIC_BASELINE)
    command.upgrade(cfg, "head")


def _has_post_baseline_schema(sync_conn) -> bool:
    """True if the ``user`` table's schema is post-baseline (matches head), not the
    pre-Alembic baseline. Used to tell a genuine pre-Alembic database (stamp the baseline,
    then upgrade) apart from an unstamped ``create_all``'d head schema left by an aborted
    test run (stamp head; #199).

    Discriminator: ``user.created_at`` is a naive timestamp in the baseline schema and was
    converted to timestamptz by the first post-baseline migration (``a1b2c3d4e5f6``) — and
    ``create_all`` (from models.py) produces timestamptz — so tz-aware ⟹ post-baseline,
    naive ⟹ baseline. Defaults to False (baseline) if ``created_at`` is somehow absent, so a
    genuine pre-Alembic production database still adopts via the baseline stamp.
    """
    for col in inspect(sync_conn).get_columns("user"):
        if col["name"] == "created_at":
            return bool(getattr(col["type"], "timezone", False))
    return False


def _is_falsely_stamped_baseline(sync_conn, current: str) -> bool:
    """True if the database was corrupted by the retired stamp-to-head adoption (#143).

    That bug stamped a baseline-schema database at a post-baseline revision without
    running any DDL. The *first* post-baseline migration (``a1b2c3d4e5f6``) converted
    every timestamp column to timestamptz, so a database claiming any revision past
    the baseline while ``user.created_at`` is still a naive timestamp can only be
    the false stamp — a legitimately upgraded database always has timestamptz there.
    """
    if current == _PRE_ALEMBIC_BASELINE:
        return False
    insp = inspect(sync_conn)
    if "user" not in insp.get_table_names():
        # Stamped but empty — `_run_migrations` handles this upstream now (#113),
        # so this is unreachable from there; kept defensive so the column check
        # below can never hit a missing table.
        return False
    for col in insp.get_columns("user"):
        if col["name"] == "created_at":
            return not getattr(col["type"], "timezone", True)
    return False


async def init_db() -> None:
    async with engine.connect() as conn:
        await conn.run_sync(_run_migrations)
        # Persist the alembic_version row: the connection is not in autocommit, so
        # the version INSERT (DML) would otherwise be rolled back when it closes.
        await conn.commit()


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    async with AsyncSession(engine) as session:
        yield session
