apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceberg-ebs.fullname" . }}
  labels:
    {{- include "iceberg-ebs.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.icebergEbs.adminPassword | required "icebergEbs.adminPassword is required" | quote }}
  secret-key:     {{ .Values.icebergEbs.secretKey     | required "icebergEbs.secretKey is required"     | quote }}
