apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marvin.fullname" . }}
  labels:
    {{- include "marvin.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.marvin.adminPassword | required "marvin.adminPassword is required" | quote }}
  secret-key:     {{ .Values.marvin.secretKey     | required "marvin.secretKey is required"     | quote }}
