apiVersion: v1
kind: Service
metadata:
  name: {{ include "marvin.fullname" . }}
  labels:
    {{- include "marvin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "marvin.selectorLabels" . | nindent 4 }}
